import { adminDb } from "@/lib/firebase-admin";
import { DEFAULT_MEGA_MENU, buildMegaMenuFromCategories } from "@/lib/mega-menu";

export async function GET() {
  try {
    if (!adminDb) {
      return Response.json({ error: "Database not initialized" }, { status: 500 });
    }

    const docSnap = await adminDb.collection("settings").doc("megaMenu").get();
    let menu = null;
    if (docSnap.exists && docSnap.data().items?.length > 0) {
      menu = docSnap.data().items;
    }

    // Also fetch categories to allow auto-syncing / previewing
    const catSnap = await adminDb.collection("categories").orderBy("displayOrder", "asc").get();
    const categories = [];
    catSnap.forEach(doc => {
      categories.push({ id: doc.id, ...doc.data() });
    });

    const autoGenerated = buildMegaMenuFromCategories(categories);

    return Response.json({
      menu: menu || autoGenerated,
      isCustomized: Boolean(menu),
      categories,
      autoGenerated,
      updatedAt: docSnap.exists ? docSnap.data().updatedAt : null
    });
  } catch (error) {
    console.error("GET Admin Mega Menu error:", error);
    return Response.json({ error: error.message }, { status: 500 });
  }
}

export async function POST(req) {
  try {
    if (!adminDb) {
      return Response.json({ error: "Database not initialized" }, { status: 500 });
    }

    const body = await req.json();
    const { items, resetToDefault } = body;

    if (resetToDefault) {
      await adminDb.collection("settings").doc("megaMenu").delete();
      return Response.json({ success: true, message: "Mega menu reset to default structure." });
    }

    if (!Array.isArray(items)) {
      return Response.json({ error: "Items array is required" }, { status: 400 });
    }

    await adminDb.collection("settings").doc("megaMenu").set({
      items,
      updatedAt: new Date().toISOString()
    });

    return Response.json({ success: true, message: "Mega menu successfully saved!" });
  } catch (error) {
    console.error("POST Admin Mega Menu error:", error);
    return Response.json({ error: error.message }, { status: 500 });
  }
}
